---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
http.host: 0.0.0.0

node.name: logstash


input.file:
  path: C:\Users\svjra\Documents\git\Springboot\order-service\app-logs\ecom-log
  start_position: beginning

output.elasticsearch:
  hosts: localhost:9200
  index: checkout_index

stdout.codec: rubydebug
